//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/rxjava-1.1.6-sources/rx/internal/schedulers/SchedulerLifecycle.java
//

#include "J2ObjC_source.h"
#include "rx/internal/schedulers/SchedulerLifecycle.h"

@interface RxInternalSchedulersSchedulerLifecycle : NSObject

@end

@implementation RxInternalSchedulersSchedulerLifecycle

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "start", "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { "shutdown", "V", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  static const J2ObjcClassInfo _RxInternalSchedulersSchedulerLifecycle = { "SchedulerLifecycle", "rx.internal.schedulers", NULL, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_RxInternalSchedulersSchedulerLifecycle;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RxInternalSchedulersSchedulerLifecycle)
