//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/rxjava-1.1.6-sources/rx/functions/Action.java
//

#include "J2ObjC_source.h"
#include "rx/functions/Action.h"

@interface RxFunctionsAction : NSObject

@end

@implementation RxFunctionsAction

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _RxFunctionsAction = { "Action", "rx.functions", NULL, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, -1, -1 };
  return &_RxFunctionsAction;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RxFunctionsAction)
