//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/rxjava-1.1.6-sources/rx/functions/Func4.java
//

#include "J2ObjC_source.h"
#include "rx/functions/Func4.h"

@interface RxFunctionsFunc4 : NSObject

@end

@implementation RxFunctionsFunc4

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "callWithId:withId:withId:withId:", "LNSObject;", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { "call", "LNSObject;LNSObject;LNSObject;LNSObject;", "(TT1;TT2;TT3;TT4;)TR;", "<T1:Ljava/lang/Object;T2:Ljava/lang/Object;T3:Ljava/lang/Object;T4:Ljava/lang/Object;R:Ljava/lang/Object;>Ljava/lang/Object;Lrx/functions/Function;" };
  static const J2ObjcClassInfo _RxFunctionsFunc4 = { "Func4", "rx.functions", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 3, -1 };
  return &_RxFunctionsFunc4;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RxFunctionsFunc4)
