//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/rxjava-1.1.6-sources/rx/internal/operators/SingleOperatorOnErrorResumeNext.java
//

/*!
 @brief Copyright 2016 Netflix, Inc.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not
 use this file except in compliance with the License. You may obtain a copy of
 the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 License for the specific language governing permissions and limitations under
 the License.
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxInternalOperatorsSingleOperatorOnErrorResumeNext")
#ifdef RESTRICT_RxInternalOperatorsSingleOperatorOnErrorResumeNext
#define INCLUDE_ALL_RxInternalOperatorsSingleOperatorOnErrorResumeNext 0
#else
#define INCLUDE_ALL_RxInternalOperatorsSingleOperatorOnErrorResumeNext 1
#endif
#undef RESTRICT_RxInternalOperatorsSingleOperatorOnErrorResumeNext

#if !defined (RxInternalOperatorsSingleOperatorOnErrorResumeNext_) && (INCLUDE_ALL_RxInternalOperatorsSingleOperatorOnErrorResumeNext || defined(INCLUDE_RxInternalOperatorsSingleOperatorOnErrorResumeNext))
#define RxInternalOperatorsSingleOperatorOnErrorResumeNext_

#define RESTRICT_RxSingle 1
#define INCLUDE_RxSingle_OnSubscribe 1
#include "rx/Single.h"

@class RxSingle;
@class RxSingleSubscriber;
@protocol RxFunctionsFunc1;

@interface RxInternalOperatorsSingleOperatorOnErrorResumeNext : NSObject < RxSingle_OnSubscribe >

#pragma mark Public

- (void)callWithId:(RxSingleSubscriber *)child;

+ (RxInternalOperatorsSingleOperatorOnErrorResumeNext *)withFunctionWithRxSingle:(RxSingle *)originalSingle
                                                            withRxFunctionsFunc1:(id<RxFunctionsFunc1>)resumeFunctionInCaseOfError;

+ (RxInternalOperatorsSingleOperatorOnErrorResumeNext *)withOtherWithRxSingle:(RxSingle *)originalSingle
                                                                 withRxSingle:(RxSingle *)resumeSingleInCaseOfError;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsSingleOperatorOnErrorResumeNext)

FOUNDATION_EXPORT RxInternalOperatorsSingleOperatorOnErrorResumeNext *RxInternalOperatorsSingleOperatorOnErrorResumeNext_withFunctionWithRxSingle_withRxFunctionsFunc1_(RxSingle *originalSingle, id<RxFunctionsFunc1> resumeFunctionInCaseOfError);

FOUNDATION_EXPORT RxInternalOperatorsSingleOperatorOnErrorResumeNext *RxInternalOperatorsSingleOperatorOnErrorResumeNext_withOtherWithRxSingle_withRxSingle_(RxSingle *originalSingle, RxSingle *resumeSingleInCaseOfError);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsSingleOperatorOnErrorResumeNext)

#endif

#pragma pop_macro("INCLUDE_ALL_RxInternalOperatorsSingleOperatorOnErrorResumeNext")
