//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/rxjava-1.1.6-sources/rx/plugins/RxJavaObservableExecutionHook.java
//

#include "J2ObjC_source.h"
#include "rx/Observable.h"
#include "rx/Subscription.h"
#include "rx/plugins/RxJavaObservableExecutionHook.h"

@implementation RxPluginsRxJavaObservableExecutionHook

- (id<RxObservable_OnSubscribe>)onCreateWithRxObservable_OnSubscribe:(id<RxObservable_OnSubscribe>)f {
  return f;
}

- (id<RxObservable_OnSubscribe>)onSubscribeStartWithRxObservable:(RxObservable *)observableInstance
                                    withRxObservable_OnSubscribe:(id<RxObservable_OnSubscribe>)onSubscribe {
  return onSubscribe;
}

- (id<RxSubscription>)onSubscribeReturnWithRxSubscription:(id<RxSubscription>)subscription {
  return subscription;
}

- (NSException *)onSubscribeErrorWithNSException:(NSException *)e {
  return e;
}

- (id<RxObservable_Operator>)onLiftWithRxObservable_Operator:(id<RxObservable_Operator>)lift {
  return lift;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxPluginsRxJavaObservableExecutionHook_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onCreateWithRxObservable_OnSubscribe:", "LRxObservable_OnSubscribe;", 0x1, 0, 1, -1, 2, -1, -1 },
    { "onSubscribeStartWithRxObservable:withRxObservable_OnSubscribe:", "LRxObservable_OnSubscribe;", 0x1, 3, 4, -1, 5, -1, -1 },
    { "onSubscribeReturnWithRxSubscription:", "LRxSubscription;", 0x1, 6, 7, -1, 8, -1, -1 },
    { "onSubscribeErrorWithNSException:", "LNSException;", 0x1, 9, 10, -1, 11, -1, -1 },
    { "onLiftWithRxObservable_Operator:", "LRxObservable_Operator;", 0x1, 12, 13, -1, 14, -1, -1 },
    { "init", NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "onCreate", "LRxObservable_OnSubscribe;", "<T:Ljava/lang/Object;>(Lrx/Observable$OnSubscribe<TT;>;)Lrx/Observable$OnSubscribe<TT;>;", "onSubscribeStart", "LRxObservable;LRxObservable_OnSubscribe;", "<T:Ljava/lang/Object;>(Lrx/Observable<+TT;>;Lrx/Observable$OnSubscribe<TT;>;)Lrx/Observable$OnSubscribe<TT;>;", "onSubscribeReturn", "LRxSubscription;", "<T:Ljava/lang/Object;>(Lrx/Subscription;)Lrx/Subscription;", "onSubscribeError", "LNSException;", "<T:Ljava/lang/Object;>(Ljava/lang/Throwable;)Ljava/lang/Throwable;", "onLift", "LRxObservable_Operator;", "<T:Ljava/lang/Object;R:Ljava/lang/Object;>(Lrx/Observable$Operator<+TR;-TT;>;)Lrx/Observable$Operator<+TR;-TT;>;" };
  static const J2ObjcClassInfo _RxPluginsRxJavaObservableExecutionHook = { "RxJavaObservableExecutionHook", "rx.plugins", ptrTable, methods, NULL, 7, 0x401, 6, 0, -1, -1, -1, -1, -1 };
  return &_RxPluginsRxJavaObservableExecutionHook;
}

@end

void RxPluginsRxJavaObservableExecutionHook_init(RxPluginsRxJavaObservableExecutionHook *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxPluginsRxJavaObservableExecutionHook)
