//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/okio-1.9.0-sources/okio/Okio.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/io/File.h"
#include "java/io/FileInputStream.h"
#include "java/io/FileOutputStream.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/io/InterruptedIOException.h"
#include "java/io/OutputStream.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Exception.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Math.h"
#include "java/net/Socket.h"
#include "java/net/SocketTimeoutException.h"
#include "java/util/logging/Level.h"
#include "java/util/logging/Logger.h"
#include "okio/AsyncTimeout.h"
#include "okio/Buffer.h"
#include "okio/BufferedSink.h"
#include "okio/BufferedSource.h"
#include "okio/Okio.h"
#include "okio/RealBufferedSink.h"
#include "okio/RealBufferedSource.h"
#include "okio/Segment.h"
#include "okio/SegmentPool.h"
#include "okio/Sink.h"
#include "okio/Source.h"
#include "okio/Timeout.h"
#include "okio/Util.h"

@interface OkioOkio ()

- (instancetype)init;

+ (id<OkioSink>)sinkWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                           withOkioTimeout:(OkioTimeout *)timeout;

+ (id<OkioSource>)sourceWithJavaIoInputStream:(JavaIoInputStream *)inArg
                              withOkioTimeout:(OkioTimeout *)timeout;

+ (OkioAsyncTimeout *)timeoutWithJavaNetSocket:(JavaNetSocket *)socket;

@end

__attribute__((unused)) static void OkioOkio_init(OkioOkio *self);

__attribute__((unused)) static OkioOkio *new_OkioOkio_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OkioOkio *create_OkioOkio_init();

__attribute__((unused)) static id<OkioSink> OkioOkio_sinkWithJavaIoOutputStream_withOkioTimeout_(JavaIoOutputStream *outArg, OkioTimeout *timeout);

__attribute__((unused)) static id<OkioSource> OkioOkio_sourceWithJavaIoInputStream_withOkioTimeout_(JavaIoInputStream *inArg, OkioTimeout *timeout);

__attribute__((unused)) static OkioAsyncTimeout *OkioOkio_timeoutWithJavaNetSocket_(JavaNetSocket *socket);

@interface OkioOkio_$1 : NSObject < OkioSink > {
 @public
  OkioTimeout *val$timeout_;
  JavaIoOutputStream *val$out_;
}

- (void)writeWithOkioBuffer:(OkioBuffer *)source
                   withLong:(jlong)byteCount;

- (void)flush;

- (void)close;

- (OkioTimeout *)timeout;

- (NSString *)description;

- (instancetype)initWithOkioTimeout:(OkioTimeout *)capture$0
             withJavaIoOutputStream:(JavaIoOutputStream *)capture$1;

@end

J2OBJC_EMPTY_STATIC_INIT(OkioOkio_$1)

J2OBJC_FIELD_SETTER(OkioOkio_$1, val$timeout_, OkioTimeout *)
J2OBJC_FIELD_SETTER(OkioOkio_$1, val$out_, JavaIoOutputStream *)

__attribute__((unused)) static void OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(OkioOkio_$1 *self, OkioTimeout *capture$0, JavaIoOutputStream *capture$1);

__attribute__((unused)) static OkioOkio_$1 *new_OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(OkioTimeout *capture$0, JavaIoOutputStream *capture$1) NS_RETURNS_RETAINED;

__attribute__((unused)) static OkioOkio_$1 *create_OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(OkioTimeout *capture$0, JavaIoOutputStream *capture$1);

J2OBJC_TYPE_LITERAL_HEADER(OkioOkio_$1)

@interface OkioOkio_$2 : NSObject < OkioSource > {
 @public
  OkioTimeout *val$timeout_;
  JavaIoInputStream *val$in_;
}

- (jlong)readWithOkioBuffer:(OkioBuffer *)sink
                   withLong:(jlong)byteCount;

- (void)close;

- (OkioTimeout *)timeout;

- (NSString *)description;

- (instancetype)initWithOkioTimeout:(OkioTimeout *)capture$0
              withJavaIoInputStream:(JavaIoInputStream *)capture$1;

@end

J2OBJC_EMPTY_STATIC_INIT(OkioOkio_$2)

J2OBJC_FIELD_SETTER(OkioOkio_$2, val$timeout_, OkioTimeout *)
J2OBJC_FIELD_SETTER(OkioOkio_$2, val$in_, JavaIoInputStream *)

__attribute__((unused)) static void OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(OkioOkio_$2 *self, OkioTimeout *capture$0, JavaIoInputStream *capture$1);

__attribute__((unused)) static OkioOkio_$2 *new_OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(OkioTimeout *capture$0, JavaIoInputStream *capture$1) NS_RETURNS_RETAINED;

__attribute__((unused)) static OkioOkio_$2 *create_OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(OkioTimeout *capture$0, JavaIoInputStream *capture$1);

J2OBJC_TYPE_LITERAL_HEADER(OkioOkio_$2)

@interface OkioOkio_$3 : OkioAsyncTimeout {
 @public
  JavaNetSocket *val$socket_;
}

- (JavaIoIOException *)newTimeoutExceptionWithJavaIoIOException:(JavaIoIOException *)cause OBJC_METHOD_FAMILY_NONE;

- (void)timedOut;

- (instancetype)initWithJavaNetSocket:(JavaNetSocket *)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(OkioOkio_$3)

J2OBJC_FIELD_SETTER(OkioOkio_$3, val$socket_, JavaNetSocket *)

__attribute__((unused)) static void OkioOkio_$3_initWithJavaNetSocket_(OkioOkio_$3 *self, JavaNetSocket *capture$0);

__attribute__((unused)) static OkioOkio_$3 *new_OkioOkio_$3_initWithJavaNetSocket_(JavaNetSocket *capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static OkioOkio_$3 *create_OkioOkio_$3_initWithJavaNetSocket_(JavaNetSocket *capture$0);

J2OBJC_TYPE_LITERAL_HEADER(OkioOkio_$3)

J2OBJC_INITIALIZED_DEFN(OkioOkio)

JavaUtilLoggingLogger *OkioOkio_logger;

@implementation OkioOkio

+ (JavaUtilLoggingLogger *)logger {
  return OkioOkio_logger;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OkioOkio_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (id<OkioBufferedSource>)bufferWithOkioSource:(id<OkioSource>)source {
  return OkioOkio_bufferWithOkioSource_(source);
}

+ (id<OkioBufferedSink>)bufferWithOkioSink:(id<OkioSink>)sink {
  return OkioOkio_bufferWithOkioSink_(sink);
}

+ (id<OkioSink>)sinkWithJavaIoOutputStream:(JavaIoOutputStream *)outArg {
  return OkioOkio_sinkWithJavaIoOutputStream_(outArg);
}

+ (id<OkioSink>)sinkWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                           withOkioTimeout:(OkioTimeout *)timeout {
  return OkioOkio_sinkWithJavaIoOutputStream_withOkioTimeout_(outArg, timeout);
}

+ (id<OkioSink>)sinkWithJavaNetSocket:(JavaNetSocket *)socket {
  return OkioOkio_sinkWithJavaNetSocket_(socket);
}

+ (id<OkioSource>)sourceWithJavaIoInputStream:(JavaIoInputStream *)inArg {
  return OkioOkio_sourceWithJavaIoInputStream_(inArg);
}

+ (id<OkioSource>)sourceWithJavaIoInputStream:(JavaIoInputStream *)inArg
                              withOkioTimeout:(OkioTimeout *)timeout {
  return OkioOkio_sourceWithJavaIoInputStream_withOkioTimeout_(inArg, timeout);
}

+ (id<OkioSource>)sourceWithJavaIoFile:(JavaIoFile *)file {
  return OkioOkio_sourceWithJavaIoFile_(file);
}

+ (id<OkioSink>)sinkWithJavaIoFile:(JavaIoFile *)file {
  return OkioOkio_sinkWithJavaIoFile_(file);
}

+ (id<OkioSink>)appendingSinkWithJavaIoFile:(JavaIoFile *)file {
  return OkioOkio_appendingSinkWithJavaIoFile_(file);
}

+ (id<OkioSource>)sourceWithJavaNetSocket:(JavaNetSocket *)socket {
  return OkioOkio_sourceWithJavaNetSocket_(socket);
}

+ (OkioAsyncTimeout *)timeoutWithJavaNetSocket:(JavaNetSocket *)socket {
  return OkioOkio_timeoutWithJavaNetSocket_(socket);
}

+ (jboolean)isAndroidGetsocknameErrorWithJavaLangAssertionError:(JavaLangAssertionError *)e {
  return OkioOkio_isAndroidGetsocknameErrorWithJavaLangAssertionError_(e);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { "bufferWithOkioSource:", "LOkioBufferedSource;", 0x9, 0, 1, -1, -1, -1, -1 },
    { "bufferWithOkioSink:", "LOkioBufferedSink;", 0x9, 0, 2, -1, -1, -1, -1 },
    { "sinkWithJavaIoOutputStream:", "LOkioSink;", 0x9, 3, 4, -1, -1, -1, -1 },
    { "sinkWithJavaIoOutputStream:withOkioTimeout:", "LOkioSink;", 0xa, 3, 5, -1, -1, -1, -1 },
    { "sinkWithJavaNetSocket:", "LOkioSink;", 0x9, 3, 6, 7, -1, -1, -1 },
    { "sourceWithJavaIoInputStream:", "LOkioSource;", 0x9, 8, 9, -1, -1, -1, -1 },
    { "sourceWithJavaIoInputStream:withOkioTimeout:", "LOkioSource;", 0xa, 8, 10, -1, -1, -1, -1 },
    { "sourceWithJavaIoFile:", "LOkioSource;", 0x9, 8, 11, 12, -1, -1, -1 },
    { "sinkWithJavaIoFile:", "LOkioSink;", 0x9, 3, 11, 12, -1, -1, -1 },
    { "appendingSinkWithJavaIoFile:", "LOkioSink;", 0x9, 13, 11, 12, -1, -1, -1 },
    { "sourceWithJavaNetSocket:", "LOkioSource;", 0x9, 8, 6, 7, -1, -1, -1 },
    { "timeoutWithJavaNetSocket:", "LOkioAsyncTimeout;", 0xa, 14, 6, -1, -1, -1, -1 },
    { "isAndroidGetsocknameErrorWithJavaLangAssertionError:", "Z", 0x8, 15, 16, -1, -1, -1, -1 },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "logger", "LJavaUtilLoggingLogger;", .constantValue.asLong = 0, 0x18, -1, 17, -1, -1 },
  };
  static const void *ptrTable[] = { "buffer", "LOkioSource;", "LOkioSink;", "sink", "LJavaIoOutputStream;", "LJavaIoOutputStream;LOkioTimeout;", "LJavaNetSocket;", "LJavaIoIOException;", "source", "LJavaIoInputStream;", "LJavaIoInputStream;LOkioTimeout;", "LJavaIoFile;", "LJavaIoFileNotFoundException;", "appendingSink", "timeout", "isAndroidGetsocknameError", "LJavaLangAssertionError;", &OkioOkio_logger };
  static const J2ObjcClassInfo _OkioOkio = { "Okio", "okio", ptrTable, methods, fields, 7, 0x11, 14, 1, -1, -1, -1, -1, -1 };
  return &_OkioOkio;
}

+ (void)initialize {
  if (self == [OkioOkio class]) {
    OkioOkio_logger = JavaUtilLoggingLogger_getLoggerWithNSString_([OkioOkio_class_() getName]);
    J2OBJC_SET_INITIALIZED(OkioOkio)
  }
}

@end

void OkioOkio_init(OkioOkio *self) {
  NSObject_init(self);
}

OkioOkio *new_OkioOkio_init() {
  J2OBJC_NEW_IMPL(OkioOkio, init)
}

OkioOkio *create_OkioOkio_init() {
  J2OBJC_CREATE_IMPL(OkioOkio, init)
}

id<OkioBufferedSource> OkioOkio_bufferWithOkioSource_(id<OkioSource> source) {
  OkioOkio_initialize();
  return new_OkioRealBufferedSource_initWithOkioSource_(source);
}

id<OkioBufferedSink> OkioOkio_bufferWithOkioSink_(id<OkioSink> sink) {
  OkioOkio_initialize();
  return new_OkioRealBufferedSink_initWithOkioSink_(sink);
}

id<OkioSink> OkioOkio_sinkWithJavaIoOutputStream_(JavaIoOutputStream *outArg) {
  OkioOkio_initialize();
  return OkioOkio_sinkWithJavaIoOutputStream_withOkioTimeout_(outArg, new_OkioTimeout_init());
}

id<OkioSink> OkioOkio_sinkWithJavaIoOutputStream_withOkioTimeout_(JavaIoOutputStream *outArg, OkioTimeout *timeout) {
  OkioOkio_initialize();
  if (outArg == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"out == null");
  if (timeout == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"timeout == null");
  return new_OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(timeout, outArg);
}

id<OkioSink> OkioOkio_sinkWithJavaNetSocket_(JavaNetSocket *socket) {
  OkioOkio_initialize();
  if (socket == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"socket == null");
  OkioAsyncTimeout *timeout = OkioOkio_timeoutWithJavaNetSocket_(socket);
  id<OkioSink> sink = OkioOkio_sinkWithJavaIoOutputStream_withOkioTimeout_([socket getOutputStream], timeout);
  return [((OkioAsyncTimeout *) nil_chk(timeout)) sinkWithOkioSink:sink];
}

id<OkioSource> OkioOkio_sourceWithJavaIoInputStream_(JavaIoInputStream *inArg) {
  OkioOkio_initialize();
  return OkioOkio_sourceWithJavaIoInputStream_withOkioTimeout_(inArg, new_OkioTimeout_init());
}

id<OkioSource> OkioOkio_sourceWithJavaIoInputStream_withOkioTimeout_(JavaIoInputStream *inArg, OkioTimeout *timeout) {
  OkioOkio_initialize();
  if (inArg == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"in == null");
  if (timeout == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"timeout == null");
  return new_OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(timeout, inArg);
}

id<OkioSource> OkioOkio_sourceWithJavaIoFile_(JavaIoFile *file) {
  OkioOkio_initialize();
  if (file == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"file == null");
  return OkioOkio_sourceWithJavaIoInputStream_(new_JavaIoFileInputStream_initWithJavaIoFile_(file));
}

id<OkioSink> OkioOkio_sinkWithJavaIoFile_(JavaIoFile *file) {
  OkioOkio_initialize();
  if (file == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"file == null");
  return OkioOkio_sinkWithJavaIoOutputStream_(new_JavaIoFileOutputStream_initWithJavaIoFile_(file));
}

id<OkioSink> OkioOkio_appendingSinkWithJavaIoFile_(JavaIoFile *file) {
  OkioOkio_initialize();
  if (file == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"file == null");
  return OkioOkio_sinkWithJavaIoOutputStream_(new_JavaIoFileOutputStream_initWithJavaIoFile_withBoolean_(file, true));
}

id<OkioSource> OkioOkio_sourceWithJavaNetSocket_(JavaNetSocket *socket) {
  OkioOkio_initialize();
  if (socket == nil) @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"socket == null");
  OkioAsyncTimeout *timeout = OkioOkio_timeoutWithJavaNetSocket_(socket);
  id<OkioSource> source = OkioOkio_sourceWithJavaIoInputStream_withOkioTimeout_([socket getInputStream], timeout);
  return [((OkioAsyncTimeout *) nil_chk(timeout)) sourceWithOkioSource:source];
}

OkioAsyncTimeout *OkioOkio_timeoutWithJavaNetSocket_(JavaNetSocket *socket) {
  OkioOkio_initialize();
  return new_OkioOkio_$3_initWithJavaNetSocket_(socket);
}

jboolean OkioOkio_isAndroidGetsocknameErrorWithJavaLangAssertionError_(JavaLangAssertionError *e) {
  OkioOkio_initialize();
  return [((JavaLangAssertionError *) nil_chk(e)) getCause] != nil && [e getMessage] != nil && [((NSString *) nil_chk([e getMessage])) contains:@"getsockname failed"];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OkioOkio)

@implementation OkioOkio_$1

- (void)writeWithOkioBuffer:(OkioBuffer *)source
                   withLong:(jlong)byteCount {
  OkioUtil_checkOffsetAndCountWithLong_withLong_withLong_(((OkioBuffer *) nil_chk(source))->size_, 0, byteCount);
  while (byteCount > 0) {
    [((OkioTimeout *) nil_chk(val$timeout_)) throwIfReached];
    OkioSegment *head = source->head_;
    jint toCopy = (jint) JavaLangMath_minWithLong_withLong_(byteCount, ((OkioSegment *) nil_chk(head))->limit_ - head->pos_);
    [((JavaIoOutputStream *) nil_chk(val$out_)) writeWithByteArray:head->data_ withInt:head->pos_ withInt:toCopy];
    head->pos_ += toCopy;
    byteCount -= toCopy;
    source->size_ -= toCopy;
    if (head->pos_ == head->limit_) {
      source->head_ = [head pop];
      OkioSegmentPool_recycleWithOkioSegment_(head);
    }
  }
}

- (void)flush {
  [((JavaIoOutputStream *) nil_chk(val$out_)) flush];
}

- (void)close {
  [((JavaIoOutputStream *) nil_chk(val$out_)) close];
}

- (OkioTimeout *)timeout {
  return val$timeout_;
}

- (NSString *)description {
  return JreStrcat("$@C", @"sink(", val$out_, ')');
}

- (instancetype)initWithOkioTimeout:(OkioTimeout *)capture$0
             withJavaIoOutputStream:(JavaIoOutputStream *)capture$1 {
  OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(self, capture$0, capture$1);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "writeWithOkioBuffer:withLong:", "V", 0x1, 0, 1, 2, -1, -1, -1 },
    { "flush", "V", 0x1, -1, -1, 2, -1, -1, -1 },
    { "close", "V", 0x1, -1, -1, 2, -1, -1, -1 },
    { "timeout", "LOkioTimeout;", 0x1, -1, -1, -1, -1, -1, -1 },
    { "description", "LNSString;", 0x1, 3, -1, -1, -1, -1, -1 },
    { "initWithOkioTimeout:withJavaIoOutputStream:", NULL, 0x0, -1, 4, -1, -1, -1, -1 },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "val$timeout_", "LOkioTimeout;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$out_", "LJavaIoOutputStream;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "write", "LOkioBuffer;J", "LJavaIoIOException;", "toString", "LOkioTimeout;LJavaIoOutputStream;", "LOkioOkio;", "sinkWithJavaIoOutputStream:withOkioTimeout:" };
  static const J2ObjcClassInfo _OkioOkio_$1 = { "", "okio", ptrTable, methods, fields, 7, 0x8008, 6, 2, 5, -1, 6, -1, -1 };
  return &_OkioOkio_$1;
}

@end

void OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(OkioOkio_$1 *self, OkioTimeout *capture$0, JavaIoOutputStream *capture$1) {
  self->val$timeout_ = capture$0;
  self->val$out_ = capture$1;
  NSObject_init(self);
}

OkioOkio_$1 *new_OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(OkioTimeout *capture$0, JavaIoOutputStream *capture$1) {
  J2OBJC_NEW_IMPL(OkioOkio_$1, initWithOkioTimeout_withJavaIoOutputStream_, capture$0, capture$1)
}

OkioOkio_$1 *create_OkioOkio_$1_initWithOkioTimeout_withJavaIoOutputStream_(OkioTimeout *capture$0, JavaIoOutputStream *capture$1) {
  J2OBJC_CREATE_IMPL(OkioOkio_$1, initWithOkioTimeout_withJavaIoOutputStream_, capture$0, capture$1)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OkioOkio_$1)

@implementation OkioOkio_$2

- (jlong)readWithOkioBuffer:(OkioBuffer *)sink
                   withLong:(jlong)byteCount {
  if (byteCount < 0) @throw new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$J", @"byteCount < 0: ", byteCount));
  if (byteCount == 0) return 0;
  @try {
    [((OkioTimeout *) nil_chk(val$timeout_)) throwIfReached];
    OkioSegment *tail = [((OkioBuffer *) nil_chk(sink)) writableSegmentWithInt:1];
    jint maxToCopy = (jint) JavaLangMath_minWithLong_withLong_(byteCount, OkioSegment_SIZE - ((OkioSegment *) nil_chk(tail))->limit_);
    jint bytesRead = [((JavaIoInputStream *) nil_chk(val$in_)) readWithByteArray:tail->data_ withInt:tail->limit_ withInt:maxToCopy];
    if (bytesRead == -1) return -1;
    tail->limit_ += bytesRead;
    sink->size_ += bytesRead;
    return bytesRead;
  }
  @catch (JavaLangAssertionError *e) {
    if (OkioOkio_isAndroidGetsocknameErrorWithJavaLangAssertionError_(e)) @throw new_JavaIoIOException_initWithNSException_(e);
    @throw e;
  }
}

- (void)close {
  [((JavaIoInputStream *) nil_chk(val$in_)) close];
}

- (OkioTimeout *)timeout {
  return val$timeout_;
}

- (NSString *)description {
  return JreStrcat("$@C", @"source(", val$in_, ')');
}

- (instancetype)initWithOkioTimeout:(OkioTimeout *)capture$0
              withJavaIoInputStream:(JavaIoInputStream *)capture$1 {
  OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(self, capture$0, capture$1);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "readWithOkioBuffer:withLong:", "J", 0x1, 0, 1, 2, -1, -1, -1 },
    { "close", "V", 0x1, -1, -1, 2, -1, -1, -1 },
    { "timeout", "LOkioTimeout;", 0x1, -1, -1, -1, -1, -1, -1 },
    { "description", "LNSString;", 0x1, 3, -1, -1, -1, -1, -1 },
    { "initWithOkioTimeout:withJavaIoInputStream:", NULL, 0x0, -1, 4, -1, -1, -1, -1 },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "val$timeout_", "LOkioTimeout;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$in_", "LJavaIoInputStream;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "read", "LOkioBuffer;J", "LJavaIoIOException;", "toString", "LOkioTimeout;LJavaIoInputStream;", "LOkioOkio;", "sourceWithJavaIoInputStream:withOkioTimeout:" };
  static const J2ObjcClassInfo _OkioOkio_$2 = { "", "okio", ptrTable, methods, fields, 7, 0x8008, 5, 2, 5, -1, 6, -1, -1 };
  return &_OkioOkio_$2;
}

@end

void OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(OkioOkio_$2 *self, OkioTimeout *capture$0, JavaIoInputStream *capture$1) {
  self->val$timeout_ = capture$0;
  self->val$in_ = capture$1;
  NSObject_init(self);
}

OkioOkio_$2 *new_OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(OkioTimeout *capture$0, JavaIoInputStream *capture$1) {
  J2OBJC_NEW_IMPL(OkioOkio_$2, initWithOkioTimeout_withJavaIoInputStream_, capture$0, capture$1)
}

OkioOkio_$2 *create_OkioOkio_$2_initWithOkioTimeout_withJavaIoInputStream_(OkioTimeout *capture$0, JavaIoInputStream *capture$1) {
  J2OBJC_CREATE_IMPL(OkioOkio_$2, initWithOkioTimeout_withJavaIoInputStream_, capture$0, capture$1)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OkioOkio_$2)

@implementation OkioOkio_$3

- (JavaIoIOException *)newTimeoutExceptionWithJavaIoIOException:(JavaIoIOException *)cause {
  JavaIoInterruptedIOException *ioe = new_JavaNetSocketTimeoutException_initWithNSString_(@"timeout");
  if (cause != nil) {
    (void) [ioe initCauseWithNSException:cause];
  }
  return ioe;
}

- (void)timedOut {
  @try {
    [((JavaNetSocket *) nil_chk(val$socket_)) close];
  }
  @catch (JavaLangException *e) {
    [((JavaUtilLoggingLogger *) nil_chk(JreLoadStatic(OkioOkio, logger))) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:JreStrcat("$@", @"Failed to close timed out socket ", val$socket_) withNSException:e];
  }
  @catch (JavaLangAssertionError *e) {
    if (OkioOkio_isAndroidGetsocknameErrorWithJavaLangAssertionError_(e)) {
      [((JavaUtilLoggingLogger *) nil_chk(JreLoadStatic(OkioOkio, logger))) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:JreStrcat("$@", @"Failed to close timed out socket ", val$socket_) withNSException:e];
    }
    else {
      @throw e;
    }
  }
}

- (instancetype)initWithJavaNetSocket:(JavaNetSocket *)capture$0 {
  OkioOkio_$3_initWithJavaNetSocket_(self, capture$0);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "newTimeoutExceptionWithJavaIoIOException:", "LJavaIoIOException;", 0x4, 0, 1, -1, -1, -1, -1 },
    { "timedOut", "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { "initWithJavaNetSocket:", NULL, 0x0, -1, 2, -1, -1, -1, -1 },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "val$socket_", "LJavaNetSocket;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "newTimeoutException", "LJavaIoIOException;", "LJavaNetSocket;", "LOkioOkio;", "timeoutWithJavaNetSocket:" };
  static const J2ObjcClassInfo _OkioOkio_$3 = { "", "okio", ptrTable, methods, fields, 7, 0x8008, 3, 1, 3, -1, 4, -1, -1 };
  return &_OkioOkio_$3;
}

@end

void OkioOkio_$3_initWithJavaNetSocket_(OkioOkio_$3 *self, JavaNetSocket *capture$0) {
  self->val$socket_ = capture$0;
  OkioAsyncTimeout_init(self);
}

OkioOkio_$3 *new_OkioOkio_$3_initWithJavaNetSocket_(JavaNetSocket *capture$0) {
  J2OBJC_NEW_IMPL(OkioOkio_$3, initWithJavaNetSocket_, capture$0)
}

OkioOkio_$3 *create_OkioOkio_$3_initWithJavaNetSocket_(JavaNetSocket *capture$0) {
  J2OBJC_CREATE_IMPL(OkioOkio_$3, initWithJavaNetSocket_, capture$0)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OkioOkio_$3)
