//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/rxjava-1.1.6-sources/rx/exceptions/OnErrorFailedException.java
//

/*!
 @brief Copyright 2014 Netflix, Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxExceptionsOnErrorFailedException")
#ifdef RESTRICT_RxExceptionsOnErrorFailedException
#define INCLUDE_ALL_RxExceptionsOnErrorFailedException 0
#else
#define INCLUDE_ALL_RxExceptionsOnErrorFailedException 1
#endif
#undef RESTRICT_RxExceptionsOnErrorFailedException

#if !defined (RxExceptionsOnErrorFailedException_) && (INCLUDE_ALL_RxExceptionsOnErrorFailedException || defined(INCLUDE_RxExceptionsOnErrorFailedException))
#define RxExceptionsOnErrorFailedException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

/*!
 @brief Represents an exception used to re-throw errors thrown from <code>Subscriber.onError(Throwable)</code>.
 <p>
 - seealso: <a href="https://github.com/ReactiveX/RxJava/issues/969">RxJava issue #969</a>
 */
@interface RxExceptionsOnErrorFailedException : JavaLangRuntimeException

#pragma mark Public

/*!
 @brief Customizes the <code>Throwable</code> with a custom message and wraps it before it is to be re-thrown as an
 <code>OnErrorFailedException</code>.
 @param message
 the message to assign to the <code>Throwable</code> to re-throw
 @param e
 the <code>Throwable</code> to re-throw; if null, a NullPointerException is constructed
 */
- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)e;

/*!
 @brief Wraps the <code>Throwable</code> before it is to be re-thrown as an <code>OnErrorFailedException</code>.
 @param e
 the <code>Throwable</code> to re-throw; if null, a NullPointerException is constructed
 */
- (instancetype)initWithNSException:(NSException *)e;

@end

J2OBJC_EMPTY_STATIC_INIT(RxExceptionsOnErrorFailedException)

FOUNDATION_EXPORT void RxExceptionsOnErrorFailedException_initWithNSString_withNSException_(RxExceptionsOnErrorFailedException *self, NSString *message, NSException *e);

FOUNDATION_EXPORT RxExceptionsOnErrorFailedException *new_RxExceptionsOnErrorFailedException_initWithNSString_withNSException_(NSString *message, NSException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxExceptionsOnErrorFailedException *create_RxExceptionsOnErrorFailedException_initWithNSString_withNSException_(NSString *message, NSException *e);

FOUNDATION_EXPORT void RxExceptionsOnErrorFailedException_initWithNSException_(RxExceptionsOnErrorFailedException *self, NSException *e);

FOUNDATION_EXPORT RxExceptionsOnErrorFailedException *new_RxExceptionsOnErrorFailedException_initWithNSException_(NSException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxExceptionsOnErrorFailedException *create_RxExceptionsOnErrorFailedException_initWithNSException_(NSException *e);

J2OBJC_TYPE_LITERAL_HEADER(RxExceptionsOnErrorFailedException)

#endif

#pragma pop_macro("INCLUDE_ALL_RxExceptionsOnErrorFailedException")
