//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: build/libs_raw/animal-sniffer-annotations-1.15-sources/org/codehaus/mojo/animal_sniffer/IgnoreJRERequirement.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement")
#ifdef RESTRICT_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement
#define INCLUDE_ALL_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement 0
#else
#define INCLUDE_ALL_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement 1
#endif
#undef RESTRICT_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement

#if !defined (OrgCodehausMojoAnimal_snifferIgnoreJRERequirement_) && (INCLUDE_ALL_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement || defined(INCLUDE_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement))
#define OrgCodehausMojoAnimal_snifferIgnoreJRERequirement_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

/*!
 @author Kohsuke Kawaguchi
 */
@protocol OrgCodehausMojoAnimal_snifferIgnoreJRERequirement < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgCodehausMojoAnimal_snifferIgnoreJRERequirement)

J2OBJC_TYPE_LITERAL_HEADER(OrgCodehausMojoAnimal_snifferIgnoreJRERequirement)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgCodehausMojoAnimal_snifferIgnoreJRERequirement")
